# Generated by Django 3.1.5 on 2021-01-21 18:25

from django.db import migrations

def create_initial_customers(apps, schema_editor):
    Customer = apps.get_model('api', 'Customer')

    Customer(id=1, name="Arisha Barron").save()
    Customer(id=2, name="Branden Gibson").save()
    Customer(id=3, name="Rhonda Church").save()
    Customer(id=4, name="Georgina Hazel").save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_customers),
    ]
